"""Konfiguracja integracji w bazie, pozycje dokumentow PZ/PW, tabela
rozliczeniowa oraz integracja SkyShop (mirror, powiazania, PIM, kolejka).

Wszystkie zmiany sa addytywne: zadna istniejaca kolumna ani tabela nie jest
modyfikowana destrukcyjnie, wiec migracja jest bezpieczna dla istniejacych
danych. Pozycje dokumentow magazynowych sa odtwarzane z zapisanych payloadow
przy najblizszej synchronizacji albo recznie:
POST /api/v1/warehouse-documents/rebuild-positions.

Revision ID: 7a3fd3aa0514
Revises: c759d9923f03
Create Date: 2026-09-08 10:14:11.608016

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7a3fd3aa0514'
down_revision = 'c759d9923f03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skyshop_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skyshop_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('parent_skyshop_id', sa.String(length=64), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skyshop_categories'))
    )
    op.create_index(op.f('ix_skyshop_categories_parent_skyshop_id'), 'skyshop_categories', ['parent_skyshop_id'], unique=False)
    op.create_index(op.f('ix_skyshop_categories_skyshop_id'), 'skyshop_categories', ['skyshop_id'], unique=True)
    op.create_table('skyshop_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skyshop_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('price_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('category_skyshop_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skyshop_products'))
    )
    op.create_index(op.f('ix_skyshop_products_category_skyshop_id'), 'skyshop_products', ['category_skyshop_id'], unique=False)
    op.create_index(op.f('ix_skyshop_products_ean'), 'skyshop_products', ['ean'], unique=False)
    op.create_index(op.f('ix_skyshop_products_name'), 'skyshop_products', ['name'], unique=False)
    op.create_index(op.f('ix_skyshop_products_sku'), 'skyshop_products', ['sku'], unique=False)
    op.create_index(op.f('ix_skyshop_products_skyshop_id'), 'skyshop_products', ['skyshop_id'], unique=True)
    op.create_table('integration_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('secret_hint', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_status', sa.String(length=20), nullable=False),
    sa.Column('verified_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_integration_accounts_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_integration_accounts_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_accounts')),
    sa.UniqueConstraint('provider', 'label', name='uq_integration_accounts_provider_label')
    )
    op.create_index(op.f('ix_integration_accounts_is_active'), 'integration_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_integration_accounts_provider'), 'integration_accounts', ['provider'], unique=False)
    op.create_table('product_contents',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('price_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_rate', sa.String(length=10), nullable=True),
    sa.Column('local_category', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_publishable', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_contents_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_product_contents_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product_contents'))
    )
    op.create_index(op.f('ix_product_contents_local_category'), 'product_contents', ['local_category'], unique=False)
    op.create_table('skyshop_category_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_category', sa.String(length=255), nullable=False),
    sa.Column('skyshop_category_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_skyshop_category_mappings_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skyshop_category_mappings')),
    sa.UniqueConstraint('local_category', name='uq_skyshop_category_mappings_local')
    )
    op.create_index(op.f('ix_skyshop_category_mappings_local_category'), 'skyshop_category_mappings', ['local_category'], unique=False)
    op.create_table('skyshop_product_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('skyshop_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('candidate_skyshop_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_pushed_stock', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_pushed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_skyshop_product_links_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_skyshop_product_links_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skyshop_product_links'))
    )
    op.create_index(op.f('ix_skyshop_product_links_product_id'), 'skyshop_product_links', ['product_id'], unique=True)
    op.create_index(op.f('ix_skyshop_product_links_skyshop_id'), 'skyshop_product_links', ['skyshop_id'], unique=False)
    op.create_index(op.f('ix_skyshop_product_links_status'), 'skyshop_product_links', ['status'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sync_jobs_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sync_jobs_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_jobs'))
    )
    op.create_index(op.f('ix_sync_jobs_created_at'), 'sync_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_jobs_job_type'), 'sync_jobs', ['job_type'], unique=False)
    op.create_index('ix_sync_jobs_pickup', 'sync_jobs', ['status', 'next_attempt_at', 'priority'], unique=False)
    op.create_index(op.f('ix_sync_jobs_product_id'), 'sync_jobs', ['product_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_provider'), 'sync_jobs', ['provider'], unique=False)
    op.create_index(op.f('ix_sync_jobs_status'), 'sync_jobs', ['status'], unique=False)
    op.create_index('uq_sync_jobs_dedupe_pending', 'sync_jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('PENDING','RUNNING')"), sqlite_where=sa.text("status IN ('PENDING','RUNNING')"))
    op.create_table('warehouse_document_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_kind', sa.String(length=20), nullable=True),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('source_action_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('product_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('mapped_product_id', sa.Integer(), nullable=True),
    sa.Column('mapping_status', sa.String(length=20), nullable=True),
    sa.Column('mapping_match_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity_unit', sa.String(length=50), nullable=True),
    sa.Column('purchase_price_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('warehouse_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['warehouse_documents.id'], name=op.f('fk_warehouse_document_positions_document_id_warehouse_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapped_product_id'], ['products.id'], name=op.f('fk_warehouse_document_positions_mapped_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_document_positions'))
    )
    op.create_index(op.f('ix_warehouse_document_positions_document_id'), 'warehouse_document_positions', ['document_id'], unique=False)
    op.create_index(op.f('ix_warehouse_document_positions_document_kind'), 'warehouse_document_positions', ['document_kind'], unique=False)
    op.create_index(op.f('ix_warehouse_document_positions_fakturownia_id'), 'warehouse_document_positions', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_warehouse_document_positions_mapped_product_id'), 'warehouse_document_positions', ['mapped_product_id'], unique=False)
    op.create_index(op.f('ix_warehouse_document_positions_mapping_status'), 'warehouse_document_positions', ['mapping_status'], unique=False)
    op.create_index(op.f('ix_warehouse_document_positions_product_fakturownia_id'), 'warehouse_document_positions', ['product_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_warehouse_document_positions_source_action_fakturownia_id'), 'warehouse_document_positions', ['source_action_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_warehouse_document_positions_warehouse_fakturownia_id'), 'warehouse_document_positions', ['warehouse_fakturownia_id'], unique=False)
    op.create_index('ix_wdp_issue_date', 'warehouse_document_positions', ['issue_date'], unique=False)
    op.create_index('ix_wdp_product_kind', 'warehouse_document_positions', ['mapped_product_id', 'document_kind'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('discrepancy_count', sa.Integer(), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], name=op.f('fk_reconciliation_runs_sync_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_reconciliation_runs_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_runs'))
    )
    op.create_index(op.f('ix_reconciliation_runs_started_at'), 'reconciliation_runs', ['started_at'], unique=False)
    op.create_table('stock_reconciliation_lines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('fakturownia_stock', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('inbound_pz', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('inbound_pw', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('outbound_documents', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sold_invoices', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('corrections', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('local_ledger_stock', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('computed_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_reconciliation_lines_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], name=op.f('fk_stock_reconciliation_lines_run_id_reconciliation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_reconciliation_lines_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_reconciliation_lines')),
    sa.UniqueConstraint('run_id', 'product_id', 'warehouse_id', name='uq_reconciliation_line')
    )
    op.create_index('ix_reconciliation_run_status', 'stock_reconciliation_lines', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_stock_reconciliation_lines_product_id'), 'stock_reconciliation_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_reconciliation_lines_run_id'), 'stock_reconciliation_lines', ['run_id'], unique=False)
    op.create_index(op.f('ix_stock_reconciliation_lines_status'), 'stock_reconciliation_lines', ['status'], unique=False)
    op.create_index(op.f('ix_stock_reconciliation_lines_warehouse_id'), 'stock_reconciliation_lines', ['warehouse_id'], unique=False)
    op.add_column('sync_runs', sa.Column('provider', sa.String(length=30), server_default='FAKTUROWNIA', nullable=False))
    op.create_index(op.f('ix_sync_runs_provider'), 'sync_runs', ['provider'], unique=False)
    op.add_column('warehouse_documents', sa.Column('positions_built_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_documents', 'positions_built_hash')
    op.drop_index(op.f('ix_sync_runs_provider'), table_name='sync_runs')
    op.drop_column('sync_runs', 'provider')
    op.drop_index(op.f('ix_stock_reconciliation_lines_warehouse_id'), table_name='stock_reconciliation_lines')
    op.drop_index(op.f('ix_stock_reconciliation_lines_status'), table_name='stock_reconciliation_lines')
    op.drop_index(op.f('ix_stock_reconciliation_lines_run_id'), table_name='stock_reconciliation_lines')
    op.drop_index(op.f('ix_stock_reconciliation_lines_product_id'), table_name='stock_reconciliation_lines')
    op.drop_index('ix_reconciliation_run_status', table_name='stock_reconciliation_lines')
    op.drop_table('stock_reconciliation_lines')
    op.drop_index(op.f('ix_reconciliation_runs_started_at'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_wdp_product_kind', table_name='warehouse_document_positions')
    op.drop_index('ix_wdp_issue_date', table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_warehouse_fakturownia_id'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_source_action_fakturownia_id'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_product_fakturownia_id'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_mapping_status'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_mapped_product_id'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_fakturownia_id'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_document_kind'), table_name='warehouse_document_positions')
    op.drop_index(op.f('ix_warehouse_document_positions_document_id'), table_name='warehouse_document_positions')
    op.drop_table('warehouse_document_positions')
    op.drop_index('uq_sync_jobs_dedupe_pending', table_name='sync_jobs', postgresql_where=sa.text("status IN ('PENDING','RUNNING')"), sqlite_where=sa.text("status IN ('PENDING','RUNNING')"))
    op.drop_index(op.f('ix_sync_jobs_status'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_provider'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_product_id'), table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_pickup', table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_job_type'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_created_at'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_skyshop_product_links_status'), table_name='skyshop_product_links')
    op.drop_index(op.f('ix_skyshop_product_links_skyshop_id'), table_name='skyshop_product_links')
    op.drop_index(op.f('ix_skyshop_product_links_product_id'), table_name='skyshop_product_links')
    op.drop_table('skyshop_product_links')
    op.drop_index(op.f('ix_skyshop_category_mappings_local_category'), table_name='skyshop_category_mappings')
    op.drop_table('skyshop_category_mappings')
    op.drop_index(op.f('ix_product_contents_local_category'), table_name='product_contents')
    op.drop_table('product_contents')
    op.drop_index(op.f('ix_integration_accounts_provider'), table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_is_active'), table_name='integration_accounts')
    op.drop_table('integration_accounts')
    op.drop_index(op.f('ix_skyshop_products_skyshop_id'), table_name='skyshop_products')
    op.drop_index(op.f('ix_skyshop_products_sku'), table_name='skyshop_products')
    op.drop_index(op.f('ix_skyshop_products_name'), table_name='skyshop_products')
    op.drop_index(op.f('ix_skyshop_products_ean'), table_name='skyshop_products')
    op.drop_index(op.f('ix_skyshop_products_category_skyshop_id'), table_name='skyshop_products')
    op.drop_table('skyshop_products')
    op.drop_index(op.f('ix_skyshop_categories_skyshop_id'), table_name='skyshop_categories')
    op.drop_index(op.f('ix_skyshop_categories_parent_skyshop_id'), table_name='skyshop_categories')
    op.drop_table('skyshop_categories')
    # ### end Alembic commands ###
