"""initial schema

Revision ID: c759d9923f03
Revises: 
Create Date: 2026-07-06 08:16:17.002741

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c759d9923f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakturownia_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_categories'))
    )
    op.create_index(op.f('ix_fakturownia_categories_fakturownia_id'), 'fakturownia_categories', ['fakturownia_id'], unique=True)
    op.create_table('fakturownia_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('tax_no', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('post_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_clients'))
    )
    op.create_index(op.f('ix_fakturownia_clients_fakturownia_id'), 'fakturownia_clients', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_fakturownia_clients_name'), 'fakturownia_clients', ['name'], unique=False)
    op.create_index(op.f('ix_fakturownia_clients_tax_no'), 'fakturownia_clients', ['tax_no'], unique=False)
    op.create_table('fakturownia_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('shortcut', sa.String(length=100), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_departments'))
    )
    op.create_index(op.f('ix_fakturownia_departments_fakturownia_id'), 'fakturownia_departments', ['fakturownia_id'], unique=True)
    op.create_table('fakturownia_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('invoice_status', sa.String(length=50), nullable=True),
    sa.Column('income', sa.Boolean(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('client_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_name', sa.String(length=500), nullable=True),
    sa.Column('buyer_tax_no', sa.String(length=50), nullable=True),
    sa.Column('seller_name', sa.String(length=500), nullable=True),
    sa.Column('department_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('warehouse_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('corrected_invoice_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_invoices'))
    )
    op.create_index(op.f('ix_fakturownia_invoices_buyer_name'), 'fakturownia_invoices', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_client_fakturownia_id'), 'fakturownia_invoices', ['client_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_corrected_invoice_fakturownia_id'), 'fakturownia_invoices', ['corrected_invoice_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_fakturownia_id'), 'fakturownia_invoices', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_fakturownia_invoices_invoice_status'), 'fakturownia_invoices', ['invoice_status'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_issue_date'), 'fakturownia_invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_kind'), 'fakturownia_invoices', ['kind'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_number'), 'fakturownia_invoices', ['number'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_sell_date'), 'fakturownia_invoices', ['sell_date'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoices_warehouse_fakturownia_id'), 'fakturownia_invoices', ['warehouse_fakturownia_id'], unique=False)
    op.create_table('fakturownia_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('invoice_fakturownia_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_payments'))
    )
    op.create_index(op.f('ix_fakturownia_payments_fakturownia_id'), 'fakturownia_payments', ['fakturownia_id'], unique=True)
    op.create_table('fakturownia_price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_price_lists'))
    )
    op.create_index(op.f('ix_fakturownia_price_lists_fakturownia_id'), 'fakturownia_price_lists', ['fakturownia_id'], unique=True)
    op.create_table('fakturownia_product_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_product_stocks')),
    sa.UniqueConstraint('product_fakturownia_id', 'warehouse_fakturownia_id', name='uq_fprod_stock_product_warehouse')
    )
    op.create_index(op.f('ix_fakturownia_product_stocks_product_fakturownia_id'), 'fakturownia_product_stocks', ['product_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_fakturownia_product_stocks_warehouse_fakturownia_id'), 'fakturownia_product_stocks', ['warehouse_fakturownia_id'], unique=False)
    op.create_table('fakturownia_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=64), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('tax', sa.String(length=20), nullable=True),
    sa.Column('price_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_service_upstream', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_products'))
    )
    op.create_index(op.f('ix_fakturownia_products_code'), 'fakturownia_products', ['code'], unique=False)
    op.create_index(op.f('ix_fakturownia_products_ean'), 'fakturownia_products', ['ean'], unique=False)
    op.create_index(op.f('ix_fakturownia_products_fakturownia_id'), 'fakturownia_products', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_fakturownia_products_name'), 'fakturownia_products', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_product_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=64), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_stock_controlled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_index(op.f('ix_products_ean'), 'products', ['ean'], unique=False)
    op.create_index(op.f('ix_products_fakturownia_product_id'), 'products', ['fakturownia_product_id'], unique=True)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_stock_controlled'), 'products', ['is_stock_controlled'], unique=False)
    op.create_index(op.f('ix_products_kind'), 'products', ['kind'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('warehouse_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_document_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('warehouse_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('product_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_actions'))
    )
    op.create_index(op.f('ix_warehouse_actions_fakturownia_id'), 'warehouse_actions', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_warehouse_actions_product_fakturownia_id'), 'warehouse_actions', ['product_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_warehouse_actions_warehouse_document_fakturownia_id'), 'warehouse_actions', ['warehouse_document_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_warehouse_actions_warehouse_fakturownia_id'), 'warehouse_actions', ['warehouse_fakturownia_id'], unique=False)
    op.create_table('warehouse_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('warehouse_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('client_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_documents'))
    )
    op.create_index(op.f('ix_warehouse_documents_fakturownia_id'), 'warehouse_documents', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_warehouse_documents_invoice_fakturownia_id'), 'warehouse_documents', ['invoice_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_warehouse_documents_issue_date'), 'warehouse_documents', ['issue_date'], unique=False)
    op.create_index(op.f('ix_warehouse_documents_kind'), 'warehouse_documents', ['kind'], unique=False)
    op.create_index(op.f('ix_warehouse_documents_number'), 'warehouse_documents', ['number'], unique=False)
    op.create_index(op.f('ix_warehouse_documents_warehouse_fakturownia_id'), 'warehouse_documents', ['warehouse_fakturownia_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses'))
    )
    op.create_index(op.f('ix_warehouses_fakturownia_id'), 'warehouses', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_object_type'), 'audit_log', ['object_type'], unique=False)
    op.create_table('fakturownia_invoice_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('product_fakturownia_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity_unit', sa.String(length=50), nullable=True),
    sa.Column('price_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_price_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_price_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax', sa.String(length=20), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('mapped_product_id', sa.Integer(), nullable=True),
    sa.Column('mapping_status', sa.String(length=20), nullable=True),
    sa.Column('mapping_match_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fakturownia_invoices.id'], name=op.f('fk_fakturownia_invoice_positions_invoice_id_fakturownia_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapped_product_id'], ['products.id'], name=op.f('fk_fakturownia_invoice_positions_mapped_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fakturownia_invoice_positions'))
    )
    op.create_index(op.f('ix_fakturownia_invoice_positions_fakturownia_id'), 'fakturownia_invoice_positions', ['fakturownia_id'], unique=True)
    op.create_index(op.f('ix_fakturownia_invoice_positions_invoice_fakturownia_id'), 'fakturownia_invoice_positions', ['invoice_fakturownia_id'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoice_positions_invoice_id'), 'fakturownia_invoice_positions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoice_positions_mapped_product_id'), 'fakturownia_invoice_positions', ['mapped_product_id'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoice_positions_mapping_status'), 'fakturownia_invoice_positions', ['mapping_status'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoice_positions_name'), 'fakturownia_invoice_positions', ['name'], unique=False)
    op.create_index(op.f('ix_fakturownia_invoice_positions_product_fakturownia_id'), 'fakturownia_invoice_positions', ['product_fakturownia_id'], unique=False)
    op.create_table('local_stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('reverses_adjustment_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_local_stock_adjustments_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_local_stock_adjustments_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reverses_adjustment_id'], ['local_stock_adjustments.id'], name=op.f('fk_local_stock_adjustments_reverses_adjustment_id_local_stock_adjustments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_local_stock_adjustments_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_stock_adjustments'))
    )
    op.create_index(op.f('ix_local_stock_adjustments_occurred_at'), 'local_stock_adjustments', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_local_stock_adjustments_product_id'), 'local_stock_adjustments', ['product_id'], unique=False)
    op.create_index(op.f('ix_local_stock_adjustments_warehouse_id'), 'local_stock_adjustments', ['warehouse_id'], unique=False)
    op.create_table('local_stock_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_local_stock_balances_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_local_stock_balances_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_stock_balances')),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_stock_balance_product_wh')
    )
    op.create_index(op.f('ix_local_stock_balances_product_id'), 'local_stock_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_local_stock_balances_warehouse_id'), 'local_stock_balances', ['warehouse_id'], unique=False)
    op.create_table('opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_opening_balances_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_opening_balances_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_opening_balances_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_balances')),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_opening_balance_product_wh')
    )
    op.create_index(op.f('ix_opening_balances_as_of_date'), 'opening_balances', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_opening_balances_product_id'), 'opening_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_opening_balances_warehouse_id'), 'opening_balances', ['warehouse_id'], unique=False)
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alias_type', sa.String(length=20), nullable=False),
    sa.Column('alias_value', sa.String(length=1000), nullable=False),
    sa.Column('alias_value_normalized', sa.String(length=1000), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_product_aliases_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_aliases_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_aliases')),
    sa.UniqueConstraint('alias_type', 'alias_value_normalized', name='uq_product_aliases_type_value')
    )
    op.create_index(op.f('ix_product_aliases_alias_value_normalized'), 'product_aliases', ['alias_value_normalized'], unique=False)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.create_table('product_bundle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_product_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['products.id'], name=op.f('fk_product_bundle_components_bundle_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], name=op.f('fk_product_bundle_components_component_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_bundle_components')),
    sa.UniqueConstraint('bundle_product_id', 'component_product_id', name='uq_bundle_component')
    )
    op.create_index(op.f('ix_product_bundle_components_bundle_product_id'), 'product_bundle_components', ['bundle_product_id'], unique=False)
    op.create_index(op.f('ix_product_bundle_components_component_product_id'), 'product_bundle_components', ['component_product_id'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_key', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_exports_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_exports'))
    )
    op.create_index(op.f('ix_report_exports_report_key'), 'report_exports', ['report_key'], unique=False)
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_filters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_filters'))
    )
    op.create_index(op.f('ix_saved_filters_table_key'), 'saved_filters', ['table_key'], unique=False)
    op.create_index(op.f('ix_saved_filters_user_id'), 'saved_filters', ['user_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_sync_runs_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_run_type'), 'sync_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_table('table_column_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_key', sa.String(length=100), nullable=False),
    sa.Column('columns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_table_column_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_column_preferences')),
    sa.UniqueConstraint('user_id', 'table_key', name='uq_column_pref_user_table')
    )
    op.create_index(op.f('ix_table_column_preferences_user_id'), 'table_column_preferences', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invoices_checked', sa.Integer(), nullable=False),
    sa.Column('positions_checked', sa.Integer(), nullable=False),
    sa.Column('issues_created', sa.Integer(), nullable=False),
    sa.Column('issues_auto_resolved', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_validation_runs_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_runs'))
    )
    op.create_index(op.f('ix_validation_runs_started_at'), 'validation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_validation_runs_status'), 'validation_runs', ['status'], unique=False)
    op.create_table('local_stock_ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_invoice_id', sa.Integer(), nullable=True),
    sa.Column('source_invoice_position_id', sa.Integer(), nullable=True),
    sa.Column('source_adjustment_id', sa.Integer(), nullable=True),
    sa.Column('source_opening_balance_id', sa.Integer(), nullable=True),
    sa.Column('source_warehouse_action_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_local_stock_ledger_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_local_stock_ledger_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_adjustment_id'], ['local_stock_adjustments.id'], name=op.f('fk_local_stock_ledger_source_adjustment_id_local_stock_adjustments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['fakturownia_invoices.id'], name=op.f('fk_local_stock_ledger_source_invoice_id_fakturownia_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_invoice_position_id'], ['fakturownia_invoice_positions.id'], name=op.f('fk_local_stock_ledger_source_invoice_position_id_fakturownia_invoice_positions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_opening_balance_id'], ['opening_balances.id'], name=op.f('fk_local_stock_ledger_source_opening_balance_id_opening_balances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_warehouse_action_id'], ['warehouse_actions.id'], name=op.f('fk_local_stock_ledger_source_warehouse_action_id_warehouse_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_local_stock_ledger_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_stock_ledger'))
    )
    op.create_index('ix_ledger_product_wh_seq', 'local_stock_ledger', ['product_id', 'warehouse_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_local_stock_ledger_movement_type'), 'local_stock_ledger', ['movement_type'], unique=False)
    op.create_index(op.f('ix_local_stock_ledger_occurred_at'), 'local_stock_ledger', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_local_stock_ledger_product_id'), 'local_stock_ledger', ['product_id'], unique=False)
    op.create_index(op.f('ix_local_stock_ledger_source_invoice_id'), 'local_stock_ledger', ['source_invoice_id'], unique=False)
    op.create_index(op.f('ix_local_stock_ledger_source_invoice_position_id'), 'local_stock_ledger', ['source_invoice_position_id'], unique=False)
    op.create_index(op.f('ix_local_stock_ledger_warehouse_id'), 'local_stock_ledger', ['warehouse_id'], unique=False)
    op.create_table('product_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=1000), nullable=True),
    sa.Column('source_code', sa.String(length=255), nullable=True),
    sa.Column('source_ean', sa.String(length=64), nullable=True),
    sa.Column('source_unit', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('example_invoice_position_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], name=op.f('fk_product_mappings_confirmed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_product_mappings_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['example_invoice_position_id'], ['fakturownia_invoice_positions.id'], name=op.f('fk_product_mappings_example_invoice_position_id_fakturownia_invoice_positions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_mappings_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_mappings'))
    )
    op.create_index(op.f('ix_product_mappings_product_id'), 'product_mappings', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_mappings_signature'), 'product_mappings', ['signature'], unique=False)
    op.create_index(op.f('ix_product_mappings_source_code'), 'product_mappings', ['source_code'], unique=False)
    op.create_index(op.f('ix_product_mappings_source_name'), 'product_mappings', ['source_name'], unique=False)
    op.create_index(op.f('ix_product_mappings_status'), 'product_mappings', ['status'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], name=op.f('fk_source_snapshots_sync_run_id_sync_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots'))
    )
    op.create_index(op.f('ix_source_snapshots_payload_hash'), 'source_snapshots', ['payload_hash'], unique=False)
    op.create_index('ix_source_snapshots_resource_external', 'source_snapshots', ['resource_type', 'external_id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('invoice_position_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stock_before', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stock_after', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('technical_description', sa.Text(), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fakturownia_invoices.id'], name=op.f('fk_validation_issues_invoice_id_fakturownia_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_position_id'], ['fakturownia_invoice_positions.id'], name=op.f('fk_validation_issues_invoice_position_id_fakturownia_invoice_positions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_validation_issues_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_validation_issues_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_validation_issues_validation_run_id_validation_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_validation_issues_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_issues'))
    )
    op.create_index(op.f('ix_validation_issues_created_at'), 'validation_issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_validation_issues_dedupe_key'), 'validation_issues', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_validation_issues_invoice_id'), 'validation_issues', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_invoice_position_id'), 'validation_issues', ['invoice_position_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_issue_type'), 'validation_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_validation_issues_product_id'), 'validation_issues', ['product_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_severity'), 'validation_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_issues_status'), 'validation_issues', ['status'], unique=False)
    op.create_index(op.f('ix_validation_issues_validation_run_id'), 'validation_issues', ['validation_run_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_warehouse_id'), 'validation_issues', ['warehouse_id'], unique=False)
    op.create_table('validation_issue_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['validation_issues.id'], name=op.f('fk_validation_issue_comments_issue_id_validation_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_validation_issue_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_issue_comments'))
    )
    op.create_index(op.f('ix_validation_issue_comments_issue_id'), 'validation_issue_comments', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_issue_comments_issue_id'), table_name='validation_issue_comments')
    op.drop_table('validation_issue_comments')
    op.drop_index(op.f('ix_validation_issues_warehouse_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_validation_run_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_status'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_severity'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_product_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_issue_type'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_invoice_position_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_invoice_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_dedupe_key'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_created_at'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index('ix_source_snapshots_resource_external', table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_payload_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_product_mappings_status'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_source_name'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_source_code'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_signature'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_product_id'), table_name='product_mappings')
    op.drop_table('product_mappings')
    op.drop_index(op.f('ix_local_stock_ledger_warehouse_id'), table_name='local_stock_ledger')
    op.drop_index(op.f('ix_local_stock_ledger_source_invoice_position_id'), table_name='local_stock_ledger')
    op.drop_index(op.f('ix_local_stock_ledger_source_invoice_id'), table_name='local_stock_ledger')
    op.drop_index(op.f('ix_local_stock_ledger_product_id'), table_name='local_stock_ledger')
    op.drop_index(op.f('ix_local_stock_ledger_occurred_at'), table_name='local_stock_ledger')
    op.drop_index(op.f('ix_local_stock_ledger_movement_type'), table_name='local_stock_ledger')
    op.drop_index('ix_ledger_product_wh_seq', table_name='local_stock_ledger')
    op.drop_table('local_stock_ledger')
    op.drop_index(op.f('ix_validation_runs_status'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_started_at'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_table_column_preferences_user_id'), table_name='table_column_preferences')
    op.drop_table('table_column_preferences')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_run_type'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_saved_filters_user_id'), table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_table_key'), table_name='saved_filters')
    op.drop_table('saved_filters')
    op.drop_index(op.f('ix_report_exports_report_key'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_product_bundle_components_component_product_id'), table_name='product_bundle_components')
    op.drop_index(op.f('ix_product_bundle_components_bundle_product_id'), table_name='product_bundle_components')
    op.drop_table('product_bundle_components')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias_value_normalized'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index(op.f('ix_opening_balances_warehouse_id'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_product_id'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_as_of_date'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index(op.f('ix_local_stock_balances_warehouse_id'), table_name='local_stock_balances')
    op.drop_index(op.f('ix_local_stock_balances_product_id'), table_name='local_stock_balances')
    op.drop_table('local_stock_balances')
    op.drop_index(op.f('ix_local_stock_adjustments_warehouse_id'), table_name='local_stock_adjustments')
    op.drop_index(op.f('ix_local_stock_adjustments_product_id'), table_name='local_stock_adjustments')
    op.drop_index(op.f('ix_local_stock_adjustments_occurred_at'), table_name='local_stock_adjustments')
    op.drop_table('local_stock_adjustments')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_product_fakturownia_id'), table_name='fakturownia_invoice_positions')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_name'), table_name='fakturownia_invoice_positions')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_mapping_status'), table_name='fakturownia_invoice_positions')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_mapped_product_id'), table_name='fakturownia_invoice_positions')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_invoice_id'), table_name='fakturownia_invoice_positions')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_invoice_fakturownia_id'), table_name='fakturownia_invoice_positions')
    op.drop_index(op.f('ix_fakturownia_invoice_positions_fakturownia_id'), table_name='fakturownia_invoice_positions')
    op.drop_table('fakturownia_invoice_positions')
    op.drop_index(op.f('ix_audit_log_object_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_fakturownia_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_warehouse_documents_warehouse_fakturownia_id'), table_name='warehouse_documents')
    op.drop_index(op.f('ix_warehouse_documents_number'), table_name='warehouse_documents')
    op.drop_index(op.f('ix_warehouse_documents_kind'), table_name='warehouse_documents')
    op.drop_index(op.f('ix_warehouse_documents_issue_date'), table_name='warehouse_documents')
    op.drop_index(op.f('ix_warehouse_documents_invoice_fakturownia_id'), table_name='warehouse_documents')
    op.drop_index(op.f('ix_warehouse_documents_fakturownia_id'), table_name='warehouse_documents')
    op.drop_table('warehouse_documents')
    op.drop_index(op.f('ix_warehouse_actions_warehouse_fakturownia_id'), table_name='warehouse_actions')
    op.drop_index(op.f('ix_warehouse_actions_warehouse_document_fakturownia_id'), table_name='warehouse_actions')
    op.drop_index(op.f('ix_warehouse_actions_product_fakturownia_id'), table_name='warehouse_actions')
    op.drop_index(op.f('ix_warehouse_actions_fakturownia_id'), table_name='warehouse_actions')
    op.drop_table('warehouse_actions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_kind'), table_name='products')
    op.drop_index(op.f('ix_products_is_stock_controlled'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_fakturownia_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_ean'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_fakturownia_products_name'), table_name='fakturownia_products')
    op.drop_index(op.f('ix_fakturownia_products_fakturownia_id'), table_name='fakturownia_products')
    op.drop_index(op.f('ix_fakturownia_products_ean'), table_name='fakturownia_products')
    op.drop_index(op.f('ix_fakturownia_products_code'), table_name='fakturownia_products')
    op.drop_table('fakturownia_products')
    op.drop_index(op.f('ix_fakturownia_product_stocks_warehouse_fakturownia_id'), table_name='fakturownia_product_stocks')
    op.drop_index(op.f('ix_fakturownia_product_stocks_product_fakturownia_id'), table_name='fakturownia_product_stocks')
    op.drop_table('fakturownia_product_stocks')
    op.drop_index(op.f('ix_fakturownia_price_lists_fakturownia_id'), table_name='fakturownia_price_lists')
    op.drop_table('fakturownia_price_lists')
    op.drop_index(op.f('ix_fakturownia_payments_fakturownia_id'), table_name='fakturownia_payments')
    op.drop_table('fakturownia_payments')
    op.drop_index(op.f('ix_fakturownia_invoices_warehouse_fakturownia_id'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_sell_date'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_number'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_kind'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_issue_date'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_invoice_status'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_fakturownia_id'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_corrected_invoice_fakturownia_id'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_client_fakturownia_id'), table_name='fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_invoices_buyer_name'), table_name='fakturownia_invoices')
    op.drop_table('fakturownia_invoices')
    op.drop_index(op.f('ix_fakturownia_departments_fakturownia_id'), table_name='fakturownia_departments')
    op.drop_table('fakturownia_departments')
    op.drop_index(op.f('ix_fakturownia_clients_tax_no'), table_name='fakturownia_clients')
    op.drop_index(op.f('ix_fakturownia_clients_name'), table_name='fakturownia_clients')
    op.drop_index(op.f('ix_fakturownia_clients_fakturownia_id'), table_name='fakturownia_clients')
    op.drop_table('fakturownia_clients')
    op.drop_index(op.f('ix_fakturownia_categories_fakturownia_id'), table_name='fakturownia_categories')
    op.drop_table('fakturownia_categories')
    # ### end Alembic commands ###
